name: track_image

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    camera_image:
      shape: [3, 64, 64]  # 单帧图像，Dataset会返回(horizon, 3, 64, 64)
      type: rgb
    state:        # 必须与 Dataset 中的键名一致
      shape: [6]
      type: low_dim
  action:
    shape: [3]

dataset:
  _target_: diffusion_policy.dataset.zarr_uint8_image_dataset.ZarrUint8ImageDataset
  data_path: log/sample/v1_episodes_lqr_sac/auv_data_final.zarr
  key: ['action', 'camera_image', 'state']
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.05
  max_train_episodes: 150  # 限制训练episode数量，加快实验